name: Actions with Docker Project

on:
  push:
    branches: [ "master", "dev" ]
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Bump Maven Version
        id: bump_version
        uses: mickem/gh-action-bump-maven-version@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Tag
        run: echo "VERSION=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t yaafsome/java-maven-fork:${{ env.VERSION }} --build-arg VERSION=${{ env.VERSION }} .
          docker push yaafsome/java-maven-fork:${{ env.VERSION }}

      - name: Deploy to Local Docker
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_ADDR }}
          username: ec2-user
          password: ${{ secrets.HOST_KEY }}
          script: |
            mkdir -p ~/.ssh
            ssh-keyscan -H ${{ secrets.HOST_ADDR }} >> ~/.ssh/known_hosts
            docker pull yaafsome/java-maven-fork:${{ env.VERSION }}
            docker stop github-app && docker rm github-app
            docker run --name github-app yaafsome/java-maven-fork:${{ env.VERSION }}
          
